# Permalinks
permalink:           /:categories/:title

# Setup
title:               Blogs
url:                 https://aman-godara.github.io/blogs
paginate:            1
baseurl:             "https://aman-godara.github.io/blogs"

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Aman Godara
  url:               https://aman-godara.github.io

# Custom vars
version:             2.1.0
github:
  repo:              https://github.com/aman-godara/blogs

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

plugins: [jekyll-paginate]

highlighter: rouge
