# Permalinks
#permalink:           /:categories/:title

# Setup
tagline:             'Aman Godara'
description:         'A reserved <a href="https://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
description:         'Welcome to my Blogs!'
title:               Blogs
url:                 https://aman-godara.github.io/blogs
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Aman Godara
  url:               https://aman-godara.github.io

# Custom vars
google_analytics_id: #UA-XXXX-Y
github:
  repo:              https://github.com/aman-godara/blogs


plugins:
  - jekyll-paginate

highlighter: rouge

collections:
  blogs:
    output: true
    permalink: /:path
